Repository johnmichel/Library-Detector-for-Chrome, pull requests merged in 2019-12, with the labels that each got.

#153 Update AMP links
  library/libraries.js
Labels: Enhancement

#154 Fix detection for Preact X
  library/libraries.js
Labels: Bug, Enhancement

#155 Restore popup functionality of extension
  background_scripts/main.js
  manifest.json
Labels: Bug
